name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: maythangml
          POSTGRES_PASSWORD: maythangml
          POSTGRES_DB: TIMENEST
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      env:
        TOGETHER_AI_API_KEY: ${{ secrets.TOGETHER_AI_API_KEY }}
        AWS_POSTGRES_URL: localhost
        POSTGRES_USER: maythangml
        POSTGRES_PASSWORD: maythangml
        POSTGRES_DB: TIMENEST
        POSTGRES_PORT: 5432
        MONGODB_URL: ${{ secrets.MONGODB_URL }}
        MONGDB_TIMENEST_DN_NAME: TIMENEST
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REDIRECT_URL: http://127.0.0.1:5050/authorization/auth
        FRONTEND_URL: http://127.0.0.1:5001/create-acount
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
        REDIS_URL: ${{ secrets.REDIS_URL }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      run: |
        python -m pytest tests/ -v 